name: Publish SDK

on:
    release:
        types: [created]

jobs:
    publish-package:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  cache: "npm"
            - name: Install dependencies
              run: npm i
            - name: Build the package
              run: npm run build
            - name: Login to GitHub Package Registry
              run: npm login --registry https://npm.pkg.github.com --legacy-peer-deps
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
