name: Publish SDK

on:
    release:
        types: [created]

jobs:
    publish-package:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  registry-url: "https://registry.npmjs.org"
                  scope: "@$REGISTRY_SCOPE"
            - name: Install dependencies
              run: npm i
            - name: Build the package
              run: npm run build
            - name: Publish the package
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
