name: Publish SDK

on:
    release:
        types: [created]

jobs:
    publish-package:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  registry-url: "https://npm.pkg.github.com"
            - name: Authenticate npm
              run: |
                  echo "//npm.pkg.github.com/:_authToken=$SECRET_GITHUB_TOKEN" > ~/.npmrc
                  echo "@REGISTRY_SCOPE$:registry=https://npm.pkg.github.com" >> ~/.npmrc
            - name: Install dependencies
              run: npm i
            - name: Build the package
              run: npm run build
            - name: Publish the package
              run: npm publish
